sandboxwebsitebundle_api:
    resource: "@SandboxWebsiteBundle/Controller/ApiController.php"
    type:     annotation
    prefix:   /{_locale}/api/
    requirements:
        _locale: %requiredlocales%

sandboxwebsitebundle_user:
    resource: "@SandboxWebsiteBundle/Controller/UserController.php"
    type:     annotation

sandboxwebsitebundle_offers:
    resource: "@SandboxWebsiteBundle/Controller/OfferController.php"
    type:     annotation

sandboxwebsitebundle_packages:
    resource: "@SandboxWebsiteBundle/Controller/PackageController.php"
    type:     annotation

sandboxwebsitebundle_baltica:
    resource: "@SandboxWebsiteBundle/Controller/BalticaController.php"
    type:     annotation

sandboxwebsitebundle_hotel:
    resource: "@SandboxWebsiteBundle/Controller/HotelController.php"
    type:     annotation

sandboxwebsitebundle_newsletter:
    resource: "@SandboxWebsiteBundle/Controller/NewsletterController.php"
    type:     annotation

sandboxwebsitebundle_default:
    resource: "@SandboxWebsiteBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

sandboxwebsitebundle_subscription:
    resource: "@SandboxWebsiteBundle/Controller/SubscriptionController.php"
    type:     annotation
    prefix:   /

sandboxwebsitebundle_linkstatistics:
    resource: "@SandboxWebsiteBundle/Controller/LinkStatisticsController.php"
    type:     annotation
    prefix:   /

sandboxwebsitebundle_tag:
    resource: @SandboxWebsiteBundle/Controller/TagController.php
    type:     annotation
    prefix:   /{_locale}/
    requirements:
         _locale: %requiredlocales%

sandboxwebsitebundle_satellite_admin_list:
    resource: @SandboxWebsiteBundle/Controller/SatelliteAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/satellite/
    requirements:
         _locale: %requiredlocales%

sandboxwebsitebundle_place_admin_list:
    resource: @SandboxWebsiteBundle/Controller/PlaceAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/place/
    requirements:
         _locale: %requiredlocales%


sandboxwebsitebundle_newspage_admin_list:
    resource: @SandboxWebsiteBundle/Controller/News/NewsPageAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/newspage/
    requirements:
         _locale: %requiredlocales%

sandboxwebsitebundle_newsauthor_admin_list:
    resource: @SandboxWebsiteBundle/Controller/News/NewsAuthorAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/newsauthor/
    requirements:
         _locale: %requiredlocales%

sandboxwebsitebundle_placepage_admin_list:
    resource: @SandboxWebsiteBundle/Controller/Place/PlacePageAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/placepage/
    requirements:
         _locale: %requiredlocales%

sandboxwebsitebundle_placeauthor_admin_list:
    resource: @SandboxWebsiteBundle/Controller/Place/PlaceAuthorAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/placeauthor/
    requirements:
         _locale: %requiredlocales%

sandboxwebsitebundle_companypage_admin_list:
    resource: @SandboxWebsiteBundle/Controller/Company/CompanyPageAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/companypage/
    requirements:
         _locale: %requiredlocales%

sandboxwebsitebundle_companyauthor_admin_list:
    resource: @SandboxWebsiteBundle/Controller/Company/CompanyAuthorAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/companyauthor/
    requirements:
         _locale: %requiredlocales%

sandboxwebsitebundle_articlepage_admin_list:
    resource: @SandboxWebsiteBundle/Controller/Article/ArticlePageAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/articlepage/
    requirements:
         _locale: %requiredlocales%

sandboxwebsitebundle_articleauthor_admin_list:
    resource: @SandboxWebsiteBundle/Controller/Article/ArticleAuthorAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/articleauthor/
    requirements:
         _locale: %requiredlocales%
sandboxwebsitebundle_mainimage_admin_list:
    resource: @SandboxWebsiteBundle/Controller/MainImageAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/mainimage/
    requirements:
         _locale: %requiredlocales%

sandboxwebsitebundle_topimage_admin_list:
    resource: @SandboxWebsiteBundle/Controller/TopImageAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/topimage/
    requirements:
         _locale: %requiredlocales%

sandboxwebsitebundle_subscription_admin_list:
    resource: @SandboxWebsiteBundle/Controller/SubscriptionAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/subscription/
    requirements:
         _locale: %requiredlocales%

sandboxwebsitebundle_host_admin_list:
    resource: @SandboxWebsiteBundle/Controller/HostAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/host/
    requirements:
         _locale: %requiredlocales%

sandboxwebsitebundle_googleplace_admin_list:
    resource: @SandboxWebsiteBundle/Controller/GooglePlaceAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/googleplace/
    requirements:
         _locale: %requiredlocales%

sandboxwebsitebundle_preferredtag_admin_list:
    resource: @SandboxWebsiteBundle/Controller/PreferredTagAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/preferredtag/
    requirements:
         _locale: %requiredlocales%

sandboxwebsitebundle_seomodule_admin_list:
    resource: @SandboxWebsiteBundle/Controller/SeoModuleAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/seomodule/
    requirements:
         _locale: %requiredlocales%

sandboxwebsitebundle_hotelcriteria_admin_list:
    resource: @SandboxWebsiteBundle/Controller/HotelCriteriaAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/hotelcriteria/
    requirements:
         _locale: %requiredlocales%

sandboxwebsitebundle_hotelpage_admin_list:
    resource: @SandboxWebsiteBundle/Controller/HotelPageAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/hotelpage/
    requirements:
         _locale: %requiredlocales%

sandboxwebsitebundle_packagecategory_admin_list:
    resource: @SandboxWebsiteBundle/Controller/PackageCategoryAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/packagecategory/
    requirements:
         _locale: %requiredlocales%

sandboxwebsitebundle_packagepage_admin_list:
    resource: @SandboxWebsiteBundle/Controller/PackagePageAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/packagepage/
    requirements:
         _locale: %requiredlocales%

sandboxwebsitebundle_offerpage_admin_list:
    resource: @SandboxWebsiteBundle/Controller/OfferPageAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/offerpage/
    requirements:
         _locale: %requiredlocales%

sandboxwebsitebundle_mapcategory_admin_list:
    resource: @SandboxWebsiteBundle/Controller/MapCategoryAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/mapcategory/
    requirements:
         _locale: %requiredlocales%

sandboxwebsitebundle_ad_admin_list:
    resource: @SandboxWebsiteBundle/Controller/AdAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/ad/
    requirements:
         _locale: %requiredlocales%

sandboxwebsitebundle_linkstatistics_admin_list:
    resource: @SandboxWebsiteBundle/Controller/LinkStatisticsAdminListController.php
    type:     annotation
    prefix:   /{_locale}/admin/linkstatistics/
    requirements:
         _locale: %requiredlocales%
