sandboxwebsitebundle_user:
    resource: "@SandboxWebsiteBundle/Controller/UserController.php"
    type:     annotation

sandboxwebsitebundle_offers:
    resource: "@SandboxWebsiteBundle/Controller/OfferController.php"
    type:     annotation

sandboxwebsitebundle_packages:
    resource: "@SandboxWebsiteBundle/Controller/PackageController.php"
    type:     annotation

sandboxwebsitebundle_hotel:
    resource: "@SandboxWebsiteBundle/Controller/HotelController.php"
    type:     annotation

sandboxwebsitebundle_newsletter:
    resource: "@SandboxWebsiteBundle/Controller/NewsletterController.php"
    type:     annotation

sandboxwebsitebundle_default:
    resource: "@SandboxWebsiteBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

sandboxwebsitebundle_subscription:
    resource: "@SandboxWebsiteBundle/Controller/SubscriptionController.php"
    type:     annotation
    prefix:   /

sandboxwebsitebundle_tag:
    resource: @SandboxWebsiteBundle/Controller/TagController.php
    type:     annotation

sandboxwebsitebundle_satellite_admin_list:
    resource: @SandboxWebsiteBundle/Controller/SatelliteAdminListController.php
    type:     annotation
    prefix:   /admin/satellite/
    
         

sandboxwebsitebundle_place_admin_list:
    resource: @SandboxWebsiteBundle/Controller/PlaceAdminListController.php
    type:     annotation
    prefix:   /admin/place/
    
         


sandboxwebsitebundle_newspage_admin_list:
    resource: @SandboxWebsiteBundle/Controller/News/NewsPageAdminListController.php
    type:     annotation
    prefix:   /admin/newspage/
    
         

sandboxwebsitebundle_newsauthor_admin_list:
    resource: @SandboxWebsiteBundle/Controller/News/NewsAuthorAdminListController.php
    type:     annotation
    prefix:   /admin/newsauthor/
    
         

sandboxwebsitebundle_placepage_admin_list:
    resource: @SandboxWebsiteBundle/Controller/Place/PlacePageAdminListController.php
    type:     annotation
    prefix:   /admin/placepage/
    
         

sandboxwebsitebundle_placeauthor_admin_list:
    resource: @SandboxWebsiteBundle/Controller/Place/PlaceAuthorAdminListController.php
    type:     annotation
    prefix:   /admin/placeauthor/
    
         

sandboxwebsitebundle_companypage_admin_list:
    resource: @SandboxWebsiteBundle/Controller/Company/CompanyPageAdminListController.php
    type:     annotation
    prefix:   /admin/companypage/
    
         

sandboxwebsitebundle_companyauthor_admin_list:
    resource: @SandboxWebsiteBundle/Controller/Company/CompanyAuthorAdminListController.php
    type:     annotation
    prefix:   /admin/companyauthor/
    
         

sandboxwebsitebundle_articlepage_admin_list:
    resource: @SandboxWebsiteBundle/Controller/Article/ArticlePageAdminListController.php
    type:     annotation
    prefix:   /admin/articlepage/
    
         

sandboxwebsitebundle_articleauthor_admin_list:
    resource: @SandboxWebsiteBundle/Controller/Article/ArticleAuthorAdminListController.php
    type:     annotation
    prefix:   /admin/articleauthor/
    
         
sandboxwebsitebundle_mainimage_admin_list:
    resource: @SandboxWebsiteBundle/Controller/MainImageAdminListController.php
    type:     annotation
    prefix:   /admin/mainimage/
    
         

sandboxwebsitebundle_topimage_admin_list:
    resource: @SandboxWebsiteBundle/Controller/TopImageAdminListController.php
    type:     annotation
    prefix:   /admin/topimage/
    
         

sandboxwebsitebundle_subscription_admin_list:
    resource: @SandboxWebsiteBundle/Controller/SubscriptionAdminListController.php
    type:     annotation
    prefix:   /admin/subscription/
    
         

sandboxwebsitebundle_host_admin_list:
    resource: @SandboxWebsiteBundle/Controller/HostAdminListController.php
    type:     annotation
    prefix:   /admin/host/
    
         

sandboxwebsitebundle_googleplace_admin_list:
    resource: @SandboxWebsiteBundle/Controller/GooglePlaceAdminListController.php
    type:     annotation
    prefix:   /admin/googleplace/
    
         

sandboxwebsitebundle_preferredtag_admin_list:
    resource: @SandboxWebsiteBundle/Controller/PreferredTagAdminListController.php
    type:     annotation
    prefix:   /admin/preferredtag/
    
         

sandboxwebsitebundle_seomodule_admin_list:
    resource: @SandboxWebsiteBundle/Controller/SeoModuleAdminListController.php
    type:     annotation
    prefix:   /admin/seomodule/
    
         
sandboxwebsitebundle_hotelcriteria_admin_list:
    resource: @SandboxWebsiteBundle/Controller/HotelCriteriaAdminListController.php
    type:     annotation
    prefix:   /admin/hotelcriteria/

sandboxwebsitebundle_hotelpage_admin_list:
    resource: @SandboxWebsiteBundle/Controller/HotelPageAdminListController.php
    type:     annotation
    prefix:   /admin/hotelpage/

sandboxwebsitebundle_packagecategory_admin_list:
    resource: @SandboxWebsiteBundle/Controller/PackageCategoryAdminListController.php
    type:     annotation
    prefix:   /admin/packagecategory/

sandboxwebsitebundle_packagepage_admin_list:
    resource: @SandboxWebsiteBundle/Controller/PackagePageAdminListController.php
    type:     annotation
    prefix:   /admin/packagepage/

