services:
    sandboxwebsitebundle.default_locale_listener:
        class: Sandbox\WebsiteBundle\EventListener\DefaultLocaleListener
        tags:
          - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
        arguments: [%defaultlocale%]

#Twig
    sandboxwebsitebundle.twigHostExtension:
        class: Sandbox\WebsiteBundle\Twig\Extension\HostExtension
        arguments: [@service_container]
        tags:
          - { name: twig.extension }
    sandboxwebsitebundle.twigdatetimeExtension:
        class: Sandbox\WebsiteBundle\Twig\Extension\DateTimeExtension
        tags:
          - { name: twig.extension }


#Form Fields
    sandboxwebsitebundle.form.type.imagesize:
        class: Sandbox\WebsiteBundle\Form\Type\ImageSizeType
        arguments:
            - "%liip_imagine.filter_sets%"
        tags:
            - { name: form.type, alias: image_size }

#Menu items
    sandboxwebsitebundle.menu.adaptor.mainimage:
        class: Sandbox\WebsiteBundle\Helper\Menu\MainImageMenuAdaptor
        tags:
           -  { name: 'kunstmaan_admin.menu.adaptor' }
    sandboxwebsitebundle.menu.adaptor.topimage:
        class: Sandbox\WebsiteBundle\Helper\Menu\TopImageMenuAdaptor
        tags:
          - { name: 'kunstmaan_admin.menu.adaptor' }
    sandboxwebsitebundle.menu.adaptor.subscription:
        class: Sandbox\WebsiteBundle\Helper\Menu\SubscriptionMenuAdaptor
        tags:
          - { name: 'kunstmaan_admin.menu.adaptor' }
    sandboxwebsitebundle.menu.adaptor.host:
        class: Sandbox\WebsiteBundle\Helper\Menu\HostMenuAdaptor
        tags:
          - { name: 'kunstmaan_admin.menu.adaptor' }
    sandboxwebsitebundle.menu.adaptor.preferredtags:
        class: Sandbox\WebsiteBundle\Helper\Menu\PreferredTagMenuAdaptor
        tags:
          - { name: 'kunstmaan_admin.menu.adaptor' }
    sandboxwebsitebundle.menu.adaptor.seomodule:
        class: Sandbox\WebsiteBundle\Helper\Menu\SeoModuleAdaptor
        tags:
          - { name: 'kunstmaan_admin.menu.adaptor' }


#Listeners
    sandboxwebsitebundle.form_listener:
        class: Sandbox\WebsiteBundle\EventListener\FormListener
        arguments: [%kuma_translator.managed_locales%, @service_container]
        tags:
          - { name: kernel.event_listener, event: kunstmaan_node.postPersist, method: onFormPostPersist }

    sandboxwebsitebundle.publish_listener:
        class: Sandbox\WebsiteBundle\EventListener\PublishListener
        arguments: [@service_container]
        tags:
          - { name: kernel.event_listener, event: kunstmaan_node.postPublish, method: onPostPublish }

    sandboxwebsitebundle.copypagetraslation_listener:
        class: Sandbox\WebsiteBundle\EventListener\CopyPageTranslationListener
        arguments: [@service_container]
        tags:
          - { name: kernel.event_listener, event: kunstmaan_node.copyPageTranslation, method: onCopyPageTranslation }

    sandboxwebsitebundle.adminlist_listener:
        class: Sandbox\WebsiteBundle\EventListener\AdminListListener
        arguments: [%requiredlocales%]
        tags:
          - { name: doctrine.event_listener, event: postPersist }
#          - { name: doctrine.event_listener, event: preUpdate }

    sandboxwebsitebundle.addnode_listener:
        class: Sandbox\WebsiteBundle\EventListener\AddNodeListener
        arguments: [@service_container]
        tags:
          - { name: kernel.event_listener, event: kunstmaan_node.postPersist, method: onAddNode }
          - { name: kernel.event_listener, event: kunstmaan_node.addNode, method: onAddNode }


    acme_locale.locale_listener:
        class: Sandbox\WebsiteBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%", "@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_subscriber }



    sandboxwebsitebundle.admin_menu_adaptor:
        class: Sandbox\WebsiteBundle\Helper\Menu\AdminMenuAdaptor
        arguments: ["@security.context"]
        tags:
            -  { name: 'kunstmaan_admin.menu.adaptor' }
    sandboxwebsitebundle.menu.adaptor.modules:
            class: Sandbox\WebsiteBundle\Helper\Menu\ModulesMenuAdaptor
            tags:
                -  { name: 'kunstmaan_admin.menu.adaptor' }
    sandboxwebsitebundle.news.menu.adaptor:
        class: Sandbox\WebsiteBundle\Helper\Menu\NewsMenuAdaptor
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kunstmaan_admin.menu.adaptor }

    sandboxwebsitebundle.place.menu.adaptor:
        class: Sandbox\WebsiteBundle\Helper\Menu\PlaceMenuAdaptor
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kunstmaan_admin.menu.adaptor }

    sandboxwebsitebundle.company.menu.adaptor:
        class: Sandbox\WebsiteBundle\Helper\Menu\CompanyMenuAdaptor
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kunstmaan_admin.menu.adaptor }

    sandboxwebsitebundle.article.menu.adaptor:
        class: Sandbox\WebsiteBundle\Helper\Menu\ArticleMenuAdaptor
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kunstmaan_admin.menu.adaptor }
