services:
    sandboxwebsitebundle.default_locale_listener:
        class: Sandbox\WebsiteBundle\EventListener\DefaultLocaleListener
        tags:
          - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
        arguments: [%defaultlocale%]

#Twig
    sandboxwebsitebundle.twigHostExtension:
        class: Sandbox\WebsiteBundle\Twig\Extension\HostExtension
        arguments: [@service_container]
        tags:
          - { name: twig.extension }


#Menu items
    sandboxwebsitebundle.menu.adaptor.mainimage:
        class: Sandbox\WebsiteBundle\Helper\Menu\MainImageMenuAdaptor
        tags:
           -  { name: 'kunstmaan_admin.menu.adaptor' }
    sandboxwebsitebundle.menu.adaptor.topimage:
        class: Sandbox\WebsiteBundle\Helper\Menu\TopImageMenuAdaptor
        tags:
          - { name: 'kunstmaan_admin.menu.adaptor' }
    sandboxwebsitebundle.menu.adaptor.subscription:
        class: Sandbox\WebsiteBundle\Helper\Menu\SubscriptionMenuAdaptor
        tags:
          - { name: 'kunstmaan_admin.menu.adaptor' }
    sandboxwebsitebundle.menu.adaptor.host:
        class: Sandbox\WebsiteBundle\Helper\Menu\HostMenuAdaptor
        tags:
          - { name: 'kunstmaan_admin.menu.adaptor' }
    sandboxwebsitebundle.menu.adaptor.preferredtags:
        class: Sandbox\WebsiteBundle\Helper\Menu\PreferredTagMenuAdaptor
        tags:
          - { name: 'kunstmaan_admin.menu.adaptor' }



#Listeners
    sandboxwebsitebundle.form_listener:
        class: Sandbox\WebsiteBundle\EventListener\FormListener
        arguments: [%kuma_translator.managed_locales%, @service_container]
        tags:
          - { name: kernel.event_listener, event: kunstmaan_node.postPersist, method: onFormPostPersist }

    sandboxwebsitebundle.publish_listener:
        class: Sandbox\WebsiteBundle\EventListener\PublishListener
        arguments: [@service_container]
        tags:
          - { name: kernel.event_listener, event: kunstmaan_node.postPublish, method: onPostPublish }

    sandboxwebsitebundle.adminlist_listener:
        class: Sandbox\WebsiteBundle\EventListener\AdminListListener
        arguments: [@service_container]
        tags:
          - { name: kernel.event_listener, event: kunstmaan_adminlist.postPersist, method: onAdminListPostPersist }

    sandboxwebsitebundle.addnode_listener:
        class: Sandbox\WebsiteBundle\EventListener\AddNodeListener
        arguments: [@service_container]
        tags:
          - { name: kernel.event_listener, event: kunstmaan_node.postPersist, method: onAddNode }
          - { name: kernel.event_listener, event: kunstmaan_node.addNode, method: onAddNode }






    sandboxwebsitebundle.admin_menu_adaptor:
        class: Sandbox\WebsiteBundle\Helper\Menu\AdminMenuAdaptor
        arguments: ["@security.context"]
        tags:
            -  { name: 'kunstmaan_admin.menu.adaptor' }
    sandboxwebsitebundle.menu.adaptor.modules:
            class: Sandbox\WebsiteBundle\Helper\Menu\ModulesMenuAdaptor
            tags:
                -  { name: 'kunstmaan_admin.menu.adaptor' }
    sandboxwebsitebundle.news.menu.adaptor:
        class: Sandbox\WebsiteBundle\Helper\Menu\NewsMenuAdaptor
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kunstmaan_admin.menu.adaptor }

    sandboxwebsitebundle.place.menu.adaptor:
        class: Sandbox\WebsiteBundle\Helper\Menu\PlaceMenuAdaptor
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kunstmaan_admin.menu.adaptor }

    sandboxwebsitebundle.company.menu.adaptor:
        class: Sandbox\WebsiteBundle\Helper\Menu\CompanyMenuAdaptor
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kunstmaan_admin.menu.adaptor }

    sandboxwebsitebundle.article.menu.adaptor:
        class: Sandbox\WebsiteBundle\Helper\Menu\ArticleMenuAdaptor
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kunstmaan_admin.menu.adaptor }
