imports:
    - { resource: config.yml }
    - { resource: security.singlelang.yml }

parameters:
    locale: fi
    defaultlocale: fi
    multilanguage: false

framework:
    router:
        resource: "%kernel.root_dir%/config/routing.singlelang.yml"
