imports:
    - { resource: config.yml }
    - { resource: security.yml }
parameters:
    locale: ee
    defaultlocale: ee
    multilanguage: false

framework:
    router:
        resource: "%kernel.root_dir%/config/routing.singlelang.yml"