#BCCCronManager routing
BCCCronManagerBundle:
    resource: "@BCCCronManagerBundle/Resources/config/routing.xml"
    prefix:   /cron-manager

# KunstmaanMediaBundle
_imagine:
    resource: .
    type:     imagine

KunstmaanMediaBundle:
    resource: "@KunstmaanMediaBundle/Resources/config/routing.yml"
    prefix:   /

# KunstmaanAdminBundle
KunstmaanAdminBundle:
    resource: "@KunstmaanAdminBundle/Resources/config/routing.yml"
    prefix:   /

# KunstmaanNodeBundle
KunstmaanNodeBundle:
    resource: "@KunstmaanNodeBundle/Resources/config/routing.yml"
    prefix:   /

# KunstmaanPagePartBundle
KunstmaanPagePartBundle:
    resource: "@KunstmaanPagePartBundle/Resources/config/routing.yml"
    prefix:   /

# KunstmaanFormBundle
KunstmaanFormBundle:
    resource: "@KunstmaanFormBundle/Resources/config/routing.yml"
    prefix:   /

# KunstmaanSitemapBundle
KunstmaanSitemapBundle:
    resource: "@KunstmaanSitemapBundle/Resources/config/routing.yml"
    prefix:   /

# KunstmaanTranslatorBundle
KunstmaanTranslatorBundle:
    resource: "@KunstmaanTranslatorBundle/Resources/config/routing.yml"
    prefix:   /

# KunstmaanRedirectBundle
KunstmaanRedirectBundle:
    resource: "@KunstmaanRedirectBundle/Resources/config/routing.yml"
    prefix:   /

# KunstmaanUserManagementBundle
KunstmaanUserManagementBundle:
    resource: "@KunstmaanUserManagementBundle/Resources/config/routing.yml"
    prefix:   /

# KunstmaanDashboardBundle
KunstmaanDashboardBundle:
    resource: "@KunstmaanDashboardBundle/Resources/config/routing.yml"
    prefix:   /

sandboxwebsitebundle_tag:
    resource: @SandboxWebsiteBundle/Controller/TagController.php
    type:     annotation

KunstmaanTaggingBundle:
     resource: "@KunstmaanTaggingBundle/Resources/config/routing.yml"

sandbox_website:
     resource: "@SandboxWebsiteBundle/Resources/config/routing.singlelang.yml"
     prefix:   /

Slash:
    pattern: "/{path}"
    defaults: { _controller: "SandboxWebsiteBundle:Route:slash" }
    requirements:
        path: ".+/"
Router:
    path:      /{_locale}/{countryPrefix}/{path}
    defaults:  { _controller: "SandboxWebsiteBundle:Route:path" }
    requirements:
        _locale: %requiredlocales%
        countryPrefix: visit|jkhgh
        path: ".+"