name: Information
context: information
types:
    - { name: Header, class: Kunstmaan\PagePartBundle\Entity\HeaderPagePart }
    - { name: Text, class: Kunstmaan\PagePartBundle\Entity\TextPagePart }
    - { name: Line, class: Kunstmaan\PagePartBundle\Entity\LinePagePart }
    - { name: TOC, class: Kunstmaan\PagePartBundle\Entity\TocPagePart }
    - { name: Link, class: Kunstmaan\PagePartBundle\Entity\LinkPagePart }
    - { name: 'To Top', class: Kunstmaan\PagePartBundle\Entity\ToTopPagePart }
    - { name: Image, class: Kunstmaan\MediaPagePartBundle\Entity\ImagePagePart }
    - { name: ImageThumbnail, class: Sandbox\WebsiteBundle\Entity\PageParts\ImageThumbnailPagePart }
    - { name: Download, class: Kunstmaan\MediaPagePartBundle\Entity\DownloadPagePart }
    - { name: Slide, class: Kunstmaan\MediaPagePartBundle\Entity\SlidePagePart }
    - { name: Video, class: Kunstmaan\MediaPagePartBundle\Entity\VideoPagePart }
    - { name: Audio, class: Kunstmaan\MediaPagePartBundle\Entity\AudioPagePart }
    - { name: News, class: Sandbox\WebsiteBundle\Entity\PageParts\NewsPagePart }
    - { name: GoogleMap, class: Sandbox\WebsiteBundle\Entity\PageParts\GoogleMapPagePart }
    - { name: Gallery, class: Sandbox\WebsiteBundle\Entity\PageParts\GalleryPagePart }
    - { name: HotelGallery, class: Sandbox\WebsiteBundle\Entity\PageParts\HotelGalleryPagePart }
    - { name: HotelInformation, class: Sandbox\WebsiteBundle\Entity\PageParts\HotelInformationPagePart }
